# fly.toml app configuration file generated for 2co on 2023-09-02T17:04:15-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "2co"
primary_region = "mia"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
